# Generated by Django 4.2.16 on 2024-10-05 01:41

import apps.books.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.books.helper.author_image_upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.books.helper.book_cover_upload_path),
        ),
    ]
