# Generated by Django 4.2.16 on 2024-10-06 16:05

import apps.books.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_created_by_alter_author_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.books.helper.genre_cover_upload_path),
        ),
    ]
