# Generated by Django 4.2.16 on 2024-10-05 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_image_alter_book_cover_image'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerprofile',
            name='favorite_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.genre'),
        ),
    ]
