# Generated by Django 4.2.16 on 2024-10-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_bookstatus_readinglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstatus',
            options={'verbose_name': 'Book Status', 'verbose_name_plural': 'Book Status'},
        ),
    ]
