# Generated by Django 4.2.16 on 2024-10-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_alter_bookstatus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglist',
            name='added_on',
        ),
    ]
